-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 12:27:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p5blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p5blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p5blog` DEFAULT CHARACTER SET utf8 ;
USE `p5blog` ;

-- -----------------------------------------------------
-- Table `p5blog`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`file` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `ext` VARCHAR(50) NOT NULL,
  `mime` VARCHAR(255) NOT NULL,
  `weight_kb` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p5blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`user` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avatar_file` INT NULL,
  `pseudo` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `pass` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `file_id` (`avatar_file` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`avatar_file`)
    REFERENCES `p5blog`.`file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p5blog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`post` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `feat_img_id` INT NULL,
  `title` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `slug` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `excerpt` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `content` VARCHAR(10000) NOT NULL,
  `creation_date` DATE NOT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `author_id` (`author_id` ASC) VISIBLE,
  UNIQUE INDEX `feat_img_id` (`feat_img_id` ASC) VISIBLE,
  CONSTRAINT `post_ibfk_1`
    FOREIGN KEY (`feat_img_id`)
    REFERENCES `p5blog`.`file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_ibfk_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `p5blog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p5blog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`comment` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `content` VARCHAR(10000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_date` DATE NOT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  `post_id1` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `post_id` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `p5blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `p5blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p5blog`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`token` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content` VARCHAR(10000) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `p5blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p5blog`.`user_owner_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p5blog`.`user_owner_infos` ;

CREATE TABLE IF NOT EXISTS `p5blog`.`user_owner_infos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `photo_file` INT NULL,
  `cv_file` INT NULL,
  `first_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `last_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `catch_phrase` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` USING BTREE (`user_id`) VISIBLE,
  CONSTRAINT `user_owner_infos_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `p5blog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_owner_infos_ibfk_2`
    FOREIGN KEY (`photo_file`)
    REFERENCES `p5blog`.`file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_owner_infos_ibfk_3`
    FOREIGN KEY (`cv_file`)
    REFERENCES `p5blog`.`file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
